baseURL: https://lassembleuse.github.io/amaparcellesolidaire
languageCode: fr-fr
title: AMAP’arcelle Solidaire
theme: bulma-theme
DefaultContentLanguage: fr
metaDataFormat: "yaml"
blackfriday:
  smartypantsQuotesNBSP: true
  extensions:
  - hardLineBreak
markup:
  goldmark:
    renderer:
      unsafe: true