---
label: producteur·rices
hide_body: true
fields:
- type: field_group_list
  name: Producteurices
  label: Producteur·rices
  fields:
  - type: text
    name: categorie
    label: categorie
  - type: file
    name: icone
    label: icone
    hidden: true
  - type: field_group_list
    name: producteurices
    label: producteurices
    fields:
    - type: text
      name: nom
      label: nom
    - type: text
      name: produit
      label: produit
    - type: text
      name: website
      label: site internet
    - name: image
      type: file
      config:
        maxSize: 64
      label: Image
