---
label: producteur·rices
hide_body: true
fields:
- type: field_group_list
  name: Producteurices
  label: Producteur·rices
  fields:
  - type: text
    name: categorie
    label: categorie
  - type: file
    name: icone
    label: icone
    hidden: true
  - type: field_group_list
    name: producteurices
    label: producteurices
    fields:
    - type: text
      name: nom_producteurice
      label: Nom Producteur / productrice
    - type: text
      name: nom_exploitation
      label: Nom de l'exploitation
    - type: text
      name: produit
      label: Produit
    - name: picture
      type: file
      config:
        maxSize: 64
      label: Image
    - type: textarea
      name: description
      label: Description
    - type: text
      name: website
      label: Site internet
    - type: text
      name: localisation
      label: Localisation
